---
hostname: spine01
device_type: arista_eos
mgmt_ip: 192.168.100.1
location: DC1
interfaces:
  - name: Ethernet1/1
    description: "To leaf01"
    ip_address: 10.0.0.1/31
    enabled: true

  - name: Ethernet1/2
    description: "To leaf02"
    ip_address: 10.0.0.3/31
    enabled: true

bgp:
  asn: 65000
  router_id: 192.168.100.1
  neighbors:
    - ip: 10.0.0.0
      remote_as: 65101
      description: "leaf01"
    - ip: 10.0.0.2
      remote_as: 65102
      description: "leaf02"

---


# {
#     "hostname": "spine01",
#     "device_type": "cisco_nxos",
#     "mgmt_ip": "192.168.100.1",
#     "location": "DC1",
#     "interfaces": [
#         {
#             "name": "Ethernet1/1",
#             "description": "To leaf01",
#             "ip_address": "10.0.0.1/31",
#             "enabled": True
#         },
#         {
#             "name": "Ethernet1/2",
#             "description": "To leaf02",
#             "ip_address": "10.0.0.3/31",
#             "enabled": True
#         }
#     ],
#     "bgp": {
#         "asn": 65000,
#         "router_id": "192.168.100.1",
#         "neighbors": [
#             {
#                 "ip": "10.0.0.0",
#                 "remote_as": 65101,
#                 "description": "leaf01"
#             },
#             {
#                 "ip": "10.0.0.2",
#                 "remote_as": 65102,
#                 "description": "leaf02"
#             }
#         ]
#     }
# }
